#!/usr/bin/env bash
#
# install-kiro.sh
#
# Install superpowers skills and bootstrap steering into Kiro CLI.
#
# What this does:
#   1. Creates ~/.kiro/steering/superpowers.md from the using-superpowers
#      skill content — Kiro auto-loads all steering files at session start,
#      which is how the "invoke skills before every action" bootstrap gets
#      injected (equivalent to Claude Code's SessionStart hook).
#   2. Symlinks each skill directory into ~/.kiro/skills/ so Kiro discovers
#      them as slash commands (/brainstorming, /writing-plans, etc.).
#
# Usage:
#   ./scripts/install-kiro.sh              # symlink mode (default)
#   ./scripts/install-kiro.sh --copy       # copy instead of symlink
#   ./scripts/install-kiro.sh -n           # dry run (print actions, no writes)
#
# Idempotent: safe to re-run after pulling repo updates.
# In symlink mode, skill updates in the repo are reflected immediately.
# In copy mode, re-run after pulling to refresh copied files.

set -euo pipefail

# =============================================================================
# Resolve repo root from script location
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SKILLS_SRC="$REPO_ROOT/skills"
BOOTSTRAP_SRC="$SKILLS_SRC/using-superpowers/SKILL.md"

KIRO_DIR="${HOME}/.kiro"
STEERING_DIR="$KIRO_DIR/steering"
SKILLS_DST="$KIRO_DIR/skills"
STEERING_FILE="$STEERING_DIR/superpowers.md"

# =============================================================================
# Parse args
# =============================================================================

MODE="symlink"
DRY_RUN=false

for arg in "$@"; do
  case "$arg" in
    --copy) MODE="copy" ;;
    -n|--dry-run) DRY_RUN=true ;;
    -h|--help)
      sed -n '3,22p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      exit 1
      ;;
  esac
done

# =============================================================================
# Helpers
# =============================================================================

run() {
  if $DRY_RUN; then
    echo "[dry-run] $*"
  else
    "$@"
  fi
}

log() { echo "  $*"; }

# =============================================================================
# Verify source exists
# =============================================================================

if [ ! -f "$BOOTSTRAP_SRC" ]; then
  echo "Error: bootstrap source not found: $BOOTSTRAP_SRC" >&2
  exit 1
fi

if [ ! -d "$SKILLS_SRC" ]; then
  echo "Error: skills directory not found: $SKILLS_SRC" >&2
  exit 1
fi

echo "Installing superpowers for Kiro CLI"
echo "  Source: $REPO_ROOT"
echo "  Mode:   $MODE"
$DRY_RUN && echo "  (dry run — no changes will be made)"
echo ""

# =============================================================================
# 1. Create steering file
# =============================================================================

echo "→ Steering file"

if ! $DRY_RUN; then
  mkdir -p "$STEERING_DIR"
fi

# Strip YAML frontmatter from SKILL.md (between first two --- lines) and
# prepend a brief Kiro-context header before writing to steering dir.
STRIPPED_CONTENT=$(awk '
  NR==1 && /^---/ { in_front=1; next }
  in_front && /^---/ { in_front=0; next }
  !in_front { print }
' "$BOOTSTRAP_SRC")

STEERING_CONTENT="<!-- Auto-generated by scripts/install-kiro.sh — do not edit by hand -->
<!-- Source: $BOOTSTRAP_SRC -->
<!-- Re-run install-kiro.sh after pulling repo updates -->

$STRIPPED_CONTENT"

if [ -f "$STEERING_FILE" ]; then
  log "Updating existing steering file: $STEERING_FILE"
else
  log "Creating steering file: $STEERING_FILE"
fi

if ! $DRY_RUN; then
  printf '%s\n' "$STEERING_CONTENT" > "$STEERING_FILE"
fi
log "Done"
echo ""

# =============================================================================
# 2. Install skill directories
# =============================================================================

echo "→ Skills ($MODE mode)"

if ! $DRY_RUN; then
  mkdir -p "$SKILLS_DST"
fi

for skill_dir in "$SKILLS_SRC"/*/; do
  skill_name="$(basename "$skill_dir")"
  dst="$SKILLS_DST/$skill_name"

  if [ "$MODE" = "symlink" ]; then
    if [ -L "$dst" ]; then
      log "Already linked: $skill_name"
    elif [ -e "$dst" ]; then
      log "Skipping $skill_name — exists but is not a symlink (remove manually to re-link)"
    else
      run ln -s "$skill_dir" "$dst"
      log "Linked: $skill_name"
    fi
  else
    # copy mode
    if [ -e "$dst" ]; then
      run rm -rf "$dst"
    fi
    run cp -r "$skill_dir" "$dst"
    log "Copied: $skill_name"
  fi
done

echo ""

# =============================================================================
# Summary
# =============================================================================

if $DRY_RUN; then
  echo "Dry run complete. No changes made."
else
  echo "Installation complete."
  echo ""
  echo "Next steps:"
  echo "  1. Open Kiro CLI in any workspace"
  echo "  2. Send: Let's make a react todo list"
  echo "  3. Verify /brainstorming triggers BEFORE any code is written"
  echo "  4. Confirm slash commands work: /brainstorming /writing-plans /systematic-debugging"
  echo ""
  echo "To update after pulling repo changes:"
  if [ "$MODE" = "symlink" ]; then
    echo "  Symlinks are live — skill changes take effect immediately."
    echo "  Re-run this script only to refresh the steering file."
  else
    echo "  Re-run: ./scripts/install-kiro.sh --copy"
  fi
fi
